version: "3.9"
services:
  postgres:
    build: 
      context: ./
      dockerfile: Dockerfile.postgress
    environment:
      POSTGRES_DB: root
      POSTGRES_USER: root
      POSTGRES_HOST_AUTH_METHOD: "trust"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
  bot_app:
    working_dir: /code
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 80
    build:
      context: ./
    volumes:
      - ./:/code
    depends_on:
      - postgres
    
volumes:
  postgres:
    driver: local  # is already local by default