version: "3.9"
services:
  bot_app:
    working_dir: /code
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 80
    build:
      context: ./
    volumes:
      - ./:/code
    